add_newline = true

format = """
$directory$git_branch$git_status$c$haskell$python$nodejs$rust$golang$package
[â•šâ•â•î˜Ÿ ](bold purple)"""

[character]
success_symbol = ""
error_symbol = ""

[directory]
style = "bold cyan"
read_only = " ó°Œ¾"
truncation_length = 3
truncation_symbol = "â€¦/"
format = "[â•”â•ã€](bold purple)[$path]($style)[ã€‘](bold purple)"

[git_branch]
symbol = "îœ¥ "
style = "bold magenta"
format = "[on ](bold purple)[$symbol$branch]($style)"

[git_status]
style = "bold red"
format = "[$all_status$ahead_behind]($style)"
conflicted = " ğŸ³ "
ahead = " â‡¡ "
behind = " â‡£ "
diverged = " â‡• "
up_to_date = ""
untracked = " ï”© "
stashed = " ï€œ "
modified = " ï‘ˆ "
staged = " ï‘— "
renamed = " ï‘š "
deleted = " ï‘˜ "

[c]
symbol = "î˜ "
style = "bold blue"
format = "[ via ](bold purple)[$symbol$version]($style)"
detect_extensions = ["c", "h", "cpp", "hpp", "cc", "cxx"]

[haskell]
symbol = "î· "
style = "bold magenta"
format = "[ via ](bold purple)[$symbol$version]($style)"

[python]
symbol = "ó°Œ  "
style = "bold yellow"
format = "[ via ](bold purple)[$symbol$version]($style)"
detect_extensions = ["py", "ipynb"]
detect_files = ["pyproject.toml", "requirements.txt", "poetry.lock"]

[nodejs]
symbol = "îœ˜ "
style = "bold green"
format = "[ via ](bold purple)[$symbol$version]($style)"

[rust]
symbol = "î¨ "
style = "bold red"
format = "[ via ](bold purple)[$symbol$version]($style)"

[golang]
symbol = "î˜§ "
style = "bold blue"
format = "[ via ](bold purple)[$symbol$version]($style)"

[package]
symbol = "ó°— "
style = "bold white"
format = "[ via ](bold purple)[$symbol$version]($style)"